name: flame_audio
description: Audio support for the Flame game engine. This is currently WIP and will be the place where all audio related code will live in the future.
version: 0.0.1
homepage: https://github.com/flame-engine/flame_audio

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flame: '>=0.23.0 <1.0.0'
  audioplayers: ^0.15.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4
